create table products (
    id bigint generated by default as identity primary key,
    sku varchar(50) not null,
    name varchar(150) not null,
    active boolean not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uk_products_sku unique (sku)
);

create table stocks (
    product_id bigint primary key,
    quantity bigint not null,
    version bigint not null default 0,
    constraint fk_stocks_product foreign key (product_id) references products (id),
    constraint ck_stocks_quantity_non_negative check (quantity >= 0)
);

create table purchase_orders (
    id bigint generated by default as identity primary key,
    order_number varchar(50) not null,
    status varchar(20) not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uk_purchase_orders_order_number unique (order_number),
    constraint ck_purchase_orders_status check (
        status in ('CREATED', 'RESERVED', 'CONFIRMED', 'CANCELED', 'RETURNED', 'EXPIRED')
    )
);

create table order_lines (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    quantity bigint not null,
    returned_quantity bigint not null default 0,
    constraint fk_order_lines_order foreign key (order_id) references purchase_orders (id),
    constraint fk_order_lines_product foreign key (product_id) references products (id),
    constraint ck_order_lines_quantity_positive check (quantity > 0),
    constraint ck_order_lines_returned_quantity check (
        returned_quantity >= 0 and returned_quantity <= quantity
    )
);

create index ix_order_lines_order_id on order_lines (order_id);
create index ix_order_lines_product_id on order_lines (product_id);

create table stock_ledger (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    movement_type varchar(20) not null,
    quantity_delta bigint not null,
    balance_after bigint not null,
    reference_type varchar(30),
    reference_id varchar(100),
    created_at timestamptz not null,
    constraint fk_stock_ledger_product foreign key (product_id) references products (id),
    constraint ck_stock_ledger_movement_type check (
        movement_type in ('INITIAL', 'RESERVE', 'CANCEL', 'RETURN', 'ADJUSTMENT')
    ),
    constraint ck_stock_ledger_balance_non_negative check (balance_after >= 0)
);

create index ix_stock_ledger_product_created_at
    on stock_ledger (product_id, created_at, id);

create table idempotency_keys (
    id bigint generated by default as identity primary key,
    idempotency_key varchar(100) not null,
    request_hash varchar(64) not null,
    status varchar(20) not null,
    response_status integer,
    response_body text,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uk_idempotency_keys_key unique (idempotency_key),
    constraint ck_idempotency_keys_status check (status in ('PROCESSING', 'COMPLETED', 'FAILED'))
);
